CC = g++
CFLAGS = -std=c++14 -O2 -Wall -Werror

all:
	$(CC) $(CFLAGS) myvector/myvector/iterator.h myvector/myvector/vector.h myvector/myvectormain.cpp

clean:
	rm -rf myvector/myvector/*.out myvector/myvector/*gch