all:
		g++ -o calculator/res.o calculator/calculator/main.cpp -std=c++11
run:
		./calculator/res.o '7+2*2+2*10/-3'
clean:
		rm calculator/res.o
help:   
		echo "all - cimpile\nrun - calculate expression\nclean - delete temp files"