all:
		g++ -o matrix_copy/res.o matrix_copy/matrix_copy/main.cpp -std=c++11
run:
		./matrix_copy/res.o
clean:
		rm matrix_copy/res.o
help:   
		echo "all - cimpile\nrun - matrix tests\nclean - delete temporary files"