all: sum_by_columns.o sum_by_rows.o

sum_by_columns.o: sum_by_columns.cpp
	g++ -Wall --std=c++11 sum_by_columns.cpp -o sum_by_columns
    
sum_by_rows.o: sum_by_rows.cpp
	g++ -Wall --std=c++11 sum_by_rows.cpp -o sum_by_rows 
